// Autogenerated by String Creator

namespace DiscordUtilityBot.Constants
{
    public static class Strings
    {
        public readonly static string GrantCommandDescription = "TBD";
        public readonly static string GrantCommandUserParameterName = "tbd";
        public readonly static string GrantCommandUserParameterDescription = "TBD";
        public readonly static string GrantCommandNotAllowed = "TBD";
        public readonly static string GrantCommandResponse = "TBD";
        public readonly static string GrantCommandAlreadyGrantedResponse = "TBD";
        public readonly static string RemindCommandDescription = "TBD";
    }
}
