using System;
using System.IO;

namespace StringCreator
{
    public class Program
    {
        private const string _csvPath = "strings.csv";
        private const string _csvHeader = "Key;Comment;Value";
        private const string _sampleEntry = "FirstTest;If the key is not enough, please give a small description;Displayed Text";
        private const string _anotherSample = "SecondTest;Test Comment;Test Test";

        static void Main(string[] args)
        {
            Console.WriteLine("Scanning for strings!");

#if DEBUG
            var pathToCsv = Directory.GetParent(Environment.CurrentDirectory).Parent.Parent.FullName + "\\Files\\" + _csvPath;

            if (!File.Exists(pathToCsv))
            {
                Console.WriteLine("Strings file not found! Generating a new one now..");
                using var debugWriter = File.CreateText(pathToCsv);
                debugWriter.WriteLine(_csvHeader);
                debugWriter.WriteLine(_sampleEntry);
                debugWriter.Write(_anotherSample);
                Console.WriteLine("Done! Restart the script now!");
                Environment.Exit(0);
            }
#endif

            if (!File.Exists(args[0]))
            {
                Console.WriteLine("The csv file seems to be missing! Pass it as first argument.");
                Environment.Exit(0);
            }

            // Delete string key file
            if (File.Exists(args[1]))
            {
                Console.WriteLine("Found strings file for {0} deleting it now.", args[1]);
                try
                {
                    File.Delete(args[1]);
                }
                catch
                {
                    Console.WriteLine("Couldn't delete strings file, is it in use?");
                    Environment.Exit(0);
                }
            }

            // Create new string key file
            Console.WriteLine("Creating strings file at {0}", args[1]);
            using var writer = File.CreateText(args[1]);
            writer.WriteLine("// Autogenerated by String Creator");
            writer.WriteLine("// Made by Tobias K.");
            writer.WriteLine("");
            writer.WriteLine("namespace DiscordUtilityBot.Constants");
            writer.WriteLine("{");
            writer.WriteLine("    public static class Strings");
            writer.WriteLine("    {");

            var allEntries = File.ReadAllLines(args[0]);
            for (var i = 1; i < allEntries.Length; i++)
            {
                var seperatedValues = allEntries[i].Split(';');
                Console.WriteLine("Processing key {0}", seperatedValues[0]);
                writer.WriteLine("        public readonly static string {0} = \"{1}\";", seperatedValues[0], seperatedValues[2]);
            }

            writer.WriteLine("    }");
            writer.WriteLine("}");
            Console.WriteLine("Created strings file at {0}", args[1]);
        }
    }
}
